
spring:
  datasource:
    #MySQL
    #url: jdbc:mysql://localhost:3306/site_project?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=True
    #username: root
    #password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      #MongoDB
      url:  mongodb://localhost:27017 #uri: mongodb://yourusername:yourpassword@localhost:27017/yourDB
      username: root
      password: root
      database: site_project


    #url: ${JDBC_DATABASE_URL:jdbc:h2:mem:my-samples}
    #username: ${JDBC_DATABASE_USERNAME:sa}
    #password: ${JDBC_DATABASE_PASSWORD:}

  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  pathsToMatch: /api/**

# App Properties
app:
  jwtSecret: bezKoderSecretKey
  jwtExpirationMs: 86400000

mytest:
  val: hello
